/*CREATE TYPE muscle_group AS ENUM (
  'Chest',
  'Back',
  'Quads',
  'Hamstrings',
  'Calves',
  'Triceps',
  'Biceps',
  'Shoulders',
  'Traps'
);*/

CREATE TABLE aimfit_exercises (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exercise_name TEXT NOT NULL
  --muscle muscle_group
);