CREATE TYPE week_day AS ENUM (
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
);

CREATE TABLE aimfit_workouts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER REFERENCES aimfit_users(id)
    ON DELETE SET NULL,
  day week_day,
  title TEXT NOT NULL
);