CREATE TABLE aimfit_workout_exercises (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER REFERENCES aimfit_workouts(id),
  exercise_id INTEGER REFERENCES aimfit_exercises(id)
);