CREATE TABLE aimfit_exercise_log (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  exercise_id INTEGER REFERENCES aimfit_exercises(id) ON DELETE CASCADE,
  set_count INTEGER,
  rep_count INTEGER,
  weight_count INTEGER,
  date_logged TIMESTAMPTZ DEFAULT now() NOT NULL
);